---
name: Release notes generator
description: Updates the release notes
inputs:
  duration:
    description: 'Release notes duration since. One of "last week" or "last month"'
    required: true
    default: last week
  github_token:
    description: Github Token. You can pass it as ${{ secrets.GITHUB_TOKEN }}
    required: true
outputs:
  body: # output will be available to future steps
    description: 'Content body of the notes'
runs:
  using: 'node12'
  main: 'dist/index.js'
